# Generated by Django 3.0.4 on 2020-10-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0002_auto_20201029_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='user',
        ),
    ]
