# Generated by Django 3.0.4 on 2020-10-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0003_remove_friendship_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
