# Generated by Django 3.0.4 on 2020-10-29 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201029_1336'),
        ('friendship', '0005_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='friends',
            field=models.ManyToManyField(related_name='_friendship_friends_+', to='friendship.Friendship'),
        ),
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approed', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
