# Generated by Django 3.0.4 on 2020-11-01 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201029_1336'),
        ('friendship', '0006_auto_20201029_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendshiprequest',
            old_name='is_approed',
            new_name='is_approved',
        ),
        migrations.AddField(
            model_name='friendshiprequest',
            name='to_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sent_friedship_requests', to='users.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friedship_requests', to='users.User'),
        ),
    ]
