# Generated by Django 3.0.4 on 2020-11-02 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201029_1336'),
        ('friendship', '0007_auto_20201101_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friendship', to='users.User'),
        ),
    ]
